/*
Nama : Mutiara Yulianda
Nim : 2501081012
Tanggal : 25-Juni-2026
Program : Form Travel Bus
 */
package Pratikum250626;

import javax.swing.JOptionPane;

/**
 *
 * @author Mutiara Yulianda
 */
public class FromTravelBus extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FromTravelBus.class.getName());

    /**
     * Creates new form FromTravelBus
     */
    public FromTravelBus() {
        initComponents();
        txtHarga.setEditable(false);
        txtTotal.setEditable(false);
        txtDiskon.setEditable(false);
        txtBayar.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTujuan = new javax.swing.ButtonGroup();
        lblJudul = new javax.swing.JLabel();
        lblTujuan = new javax.swing.JLabel();
        lblKelas = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        rbBkt = new javax.swing.JRadioButton();
        rbSolok = new javax.swing.JRadioButton();
        rbPar = new javax.swing.JRadioButton();
        cbKelas = new javax.swing.JComboBox<>();
        btnHarga = new javax.swing.JButton();
        lblJumlah = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        lblDiskon = new javax.swing.JLabel();
        lblBayar = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtDiskon = new javax.swing.JTextField();
        txtBayar = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnBayar = new javax.swing.JButton();
        lblUang = new javax.swing.JLabel();
        txtUang = new javax.swing.JTextField();
        lblKembalian = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJudul.setText("FORM PEMBELIAN TIKET BUS NUSANTARA");

        lblTujuan.setText("Pilihan Tujuan");

        lblKelas.setText("Pilihan Kelas");

        btnGroupTujuan.add(rbBkt);
        rbBkt.setText("Bukittingi");

        btnGroupTujuan.add(rbSolok);
        rbSolok.setText("Solok");

        btnGroupTujuan.add(rbPar);
        rbPar.setText("Pariaman");

        cbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilihan Kelas", "Ekonomi", "Bisnis", "Eksekutif" }));

        btnHarga.setText("Harga 1Tiket");
        btnHarga.addActionListener(this::btnHargaActionPerformed);

        lblJumlah.setText("Jumlah Tiket");

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(this::btnHitungActionPerformed);

        lblTotal.setText("Total Harga Pembelian");

        lblDiskon.setText("Diskon");

        lblBayar.setText("Total Pembayaran");

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(this::btnKeluarActionPerformed);

        btnBayar.setText("Bayar");
        btnBayar.addActionListener(this::btnBayarActionPerformed);

        lblUang.setText("Jumlah Uang");

        lblKembalian.setText("Uang Kembalian");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKelas)
                                    .addComponent(lblJumlah))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTotal)
                                    .addComponent(lblDiskon)
                                    .addComponent(lblBayar)
                                    .addComponent(lblUang)
                                    .addComponent(lblKembalian)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTujuan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnReset)
                                    .addComponent(rbBkt, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbSolok, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbPar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnHitung)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHarga)
                                    .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnKeluar)
                                    .addComponent(txtUang, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblJudul))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(btnBayar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTujuan)
                    .addComponent(rbBkt)
                    .addComponent(rbSolok)
                    .addComponent(rbPar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKelas)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblJumlah)
                        .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiskon)
                    .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBayar)
                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUang)
                    .addComponent(txtUang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(btnBayar)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKembalian)
                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnKeluar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHargaActionPerformed
        int kelas = (int) cbKelas.getSelectedIndex();
        
        if(!rbBkt.isSelected()&& !rbSolok.isSelected()&& !rbPar.isSelected()){
            JOptionPane.showMessageDialog(this, "Tujuan belum dipilih!!");
        }
        else if(cbKelas.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "Kelas belum dipilih!!");
        }
        else{
        switch(kelas){
            case 1 : if(rbBkt.isSelected())
                      txtHarga.setText("40000");
            else if(rbSolok.isSelected())
                      txtHarga.setText("25000");
            else
                      txtHarga.setText("15000");
            break;
            
            case 2 : if(rbBkt.isSelected())
                      txtHarga.setText("75000");
            else if(rbSolok.isSelected())
                      txtHarga.setText("55000");
            else
                      txtHarga.setText("40000");
            break;
            
            case 3 : if(rbBkt.isSelected())
                      txtHarga.setText("120000");
            else if(rbSolok.isSelected())
                      txtHarga.setText("85000");
            else
                      txtHarga.setText("60000");
            break;
        }
        }
    }//GEN-LAST:event_btnHargaActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
       int jumlah = Integer.parseInt(txtJumlah.getText());
       if(jumlah<=0){
           JOptionPane.showMessageDialog(this, "Jumlah harus lebih dari 0", "Pesan Kesalahan", JOptionPane.ERROR_MESSAGE);
           txtJumlah.setText("");
           txtJumlah.requestFocus();
       }
       
       double harga = Double.parseDouble(txtHarga.getText());
       double total = jumlah*harga;
       double diskon = 0;
       if(jumlah>=5)
           diskon = 0.1*total;
           double bayar = total - diskon;
           
           txtTotal.setText(Double.toString(total));
           txtDiskon.setText(Double.toString(diskon));
           txtBayar.setText(Double.toString(bayar));
           
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        btnGroupTujuan.clearSelection();
        cbKelas.setSelectedIndex(0);
        txtHarga.setText("");
        txtJumlah.setText("");
        txtTotal.setText("");
        txtDiskon.setText("");
        txtBayar.setText("");
        txtUang.setText("");
        txtKembalian.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        int pil = JOptionPane.showConfirmDialog(this, "Apakah ingin keluar", "Konfirmasi keluar", JOptionPane.YES_NO_OPTION);
        
        if(pil == JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        int jumlah = Integer.parseInt(txtJumlah.getText());
        double harga = Double.parseDouble(txtHarga.getText());
        double total = jumlah*harga;
        double diskon =0;
        double uang = Double.parseDouble(txtUang.getText());
       
        if(jumlah>=5)
          diskon = 0.1*total;
           double bayar = total - diskon;
           double kembali = uang - bayar;
        
        if(uang >= bayar){
            kembali = uang - bayar;
            txtKembalian.setText(Double.toString((kembali)));
        }
        else if(uang < bayar){
            JOptionPane.showMessageDialog(this,"Mohon maaf uang anda tidak cukup!! \nSilahkan lakukan kembali pembayaran!!", "Transaksi Gagal!!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FromTravelBus().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.ButtonGroup btnGroupTujuan;
    private javax.swing.JButton btnHarga;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cbKelas;
    private javax.swing.JLabel lblBayar;
    private javax.swing.JLabel lblDiskon;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblKelas;
    private javax.swing.JLabel lblKembalian;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTujuan;
    private javax.swing.JLabel lblUang;
    private javax.swing.JRadioButton rbBkt;
    private javax.swing.JRadioButton rbPar;
    private javax.swing.JRadioButton rbSolok;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtUang;
    // End of variables declaration//GEN-END:variables
}
